TreeBranchWeb/Controllers/KeysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TreeBranchWeb.Models;

namespace TreeBranchWeb.Controllers
{
    public class KeysController : Controller
    {
        private ApplicationDbContext _context;

        public KeysController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Keys
        public ActionResult Index()
        {
            var keys = _context.DichotomousKeys.ToList();
            return View(keys);
        }

        // GET: Keys/{keyName}/Use
        public ActionResult Use(string keyName)
        {
            var key = _context.GetDichotomousKeyOrNotFound(keyName);
            ViewBag.KeyName = keyName;
            return View(key);
        }

        // GET: Keys/{keyName}/View
        public ActionResult View(string keyName)
        {
            var key = _context.GetDichotomousKeyOrNotFound(keyName);
            ViewBag.KeyName = keyName;
            return View(key);
        }
    }
}

TreeBranchWeb/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using TreeBranchWeb.Models;

namespace TreeBranchWeb.Controllers
{
    public class MatchesController : Controller
    {
        private ApplicationDbContext _context;

        public MatchesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Keys/{keyName}/Matches
        public ActionResult Index(string keyName)
        {
            var key = _context.GetDichotomousKeyOrDefault(keyName);
            if (key == null) return HttpNotFound();
            ViewBag.KeyName = keyName;

            return View(key);
        }

        // GET: Keys/{keyName}/Matches/New
        public ActionResult New(string keyName)
        {
            var key = _context.GetDichotomousKeyOrDefault(keyName);
            if (key == null) return HttpNotFound();
            ViewBag.KeyName = keyName;

            if (!key.CanAddMatches())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "This key's matches are not modifiable.");
            }
            return View("MatchForm", new Match());
        }

        [HttpPost]
        public ActionResult Save()
        {
            return View();
        }
    }
}

TreeBranchWeb/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TreeBranchWeb.Migrations;
using TreeBranchWeb.Models;

namespace TreeBranchWeb.Controllers
{
    public class QuestionsController : Controller
    {
        private ApplicationDbContext _context;

        public QuestionsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Keys/{keyName}/Questions
        public ActionResult Index(string keyName)
        {
            var key = _context.GetDichotomousKeyOrDefault(keyName);
            if (key == null) return HttpNotFound();
            ViewBag.KeyName = keyName;

            return View(key);
        }

        // GET: Keys/{keyName}/Questions/New
        public ActionResult New(string keyName)
        {
            var key = _context.GetDichotomousKeyOrDefault(keyName);
            if (key == null) return HttpNotFound();
            ViewBag.KeyName = keyName;

            if (key.QuestionsFinalized)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "This key's questions are not modifiable.");
            }
            return View("QuestionForm", new Question());
        }

        // POST: /Keys/{keyName}/Questions/Save
        [HttpPost]
        public ActionResult Save(Question question, string keyName, string submitAction)
        {
            var key = _context.GetDichotomousKeyOrDefault(keyName);
            if (key == null) return HttpNotFound();
            ViewBag.KeyName = keyName;

            if (key.QuestionsFinalized)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "This key's questions are not modifiable.");
            }

            if (submitAction.Equals("save"))
            {
                if (ModelState.IsValid)
                {
                    key.Questions.Add(question);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else if (submitAction.Equals("addAnswer"))
            {
                question.Answers.Add(new Answer());
            }
            else if (submitAction.Equals("removeAnswer"))
            {
                if (question.Answers.Count > 2)
                {
                    question.Answers.Remove(question.Answers.Last());
                }
            }
            return View("QuestionForm", question);
        }
    }
}

TreeBranchWeb/Views/Keys/Index.cshtml
@model IEnumerable<TreeBranchWeb.Models.DichotomousKey>
@{
    ViewBag.Title = "All Keys";
}

<h2>All Dichotomous Keys</h2>

<div class="container">
    @foreach (var key in Model)
    {
        <div class="card col-sm-4" style="width: 18rem">
            <div class="card-body">
                <h3 class="card-title">@key.Name</h3>
                <p class="card-text">
                    <strong>@key.Questions.Count</strong> questions.
                </p>
                <p class="card-text">
                    <strong>@key.Matches.Count</strong> matches.
                </p>
                @Html.ActionLink("Use", "Use", "Keys", new { keyName = key.Name }, new { @class = "btn btn-primary" + 
                    (key.MatchesFinalized ? "" : " disabled") })
                @Html.ActionLink("View", "View", "Keys", new { keyName = key.Name }, new { @class = "btn btn-default" })
            </div>
        </div>
    }
</div>

TreeBranchWeb/Views/Keys/View.cshtml
@model TreeBranchWeb.Models.DichotomousKey
@{
    ViewBag.Title = ViewBag.KeyName + " Key";
}

<h2>@ViewBag.Title</h2>

@if (!Model.QuestionsFinalized)
{
    <div class="alert alert-warning" role="alert">
        This key has <strong>@Model.Questions.Count</strong> 
        @if (Model.Questions.Count == 1)
        {
            @:question.
        }
        else
        {
            @:questions.
        }
        Consider @Html.ActionLink("adding questions", "New", "Questions", new { keyName = Model.Name }, new { @class = "alert-link" }).
        @if (Model.CanFinalizeQuestions())
        {
            @:If there are no more questions to add, 
            Html.ActionLink("finalize questions", "Finalize", "Questions", new { keyName = Model.Name }, new { @class = "alert-link" });
            @:and move on to adding matches.
        }
    </div>
}
else if (!Model.MatchesFinalized)
{
    <div class="alert alert-warning" role="alert">
        This key has <strong>@Model.Matches.Count</strong>
        @if (Model.Matches.Count == 1)
        {
            @:match.
        }
        else
        {
            @:matches.
        }
        @if (Model.CanAddMatches())
        {
            @:You must 
            @Html.ActionLink("add matches", "New", "Matches", new { keyName = Model.Name }, new { @class = "alert-link" });
            @: before you can use this key.
        }
        else
        {
            @:This key is almost ready to use. 
            Html.ActionLink("Finalize matches", "Finalize", "Matches", new { keyName = Model.Name }, new { @class = "alert-link" });
            @: to begin using the key.
        }
    </div>
}

<ul>
    <li>
        This key's <strong>@Model.Questions.Count</strong> questions <strong>@(Model.QuestionsFinalized ? "are" : "are not")</strong> finalized.
    </li>
    <li>
        This key's <strong>@Model.Matches.Count</strong> matches <strong>@(Model.MatchesFinalized ? "are" : "are not")</strong> finalized.
    </li>
    <li>
        This key <strong>@(Model.MatchesFinalized ? "is" : "is not")</strong> ready to use.
    </li>
</ul>

@Html.ActionLink("Use Key", "Use", "Keys", new { @class = "btn btn-primary" + 
    (Model.MatchesFinalized ? "" : " disabled") })
@Html.ActionLink("View Questions", "Index", "Questions", new { keyName = Model.Name }, new { @class = "btn btn-default" })
@Html.ActionLink("View Matches", "Index", "Questions", new { keyName = Model.Name }, new { @class = "btn btn-default" })